# Generated by Django 5.0.6 on 2024-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="FirstName"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="LastName"
                    ),
                ),
                (
                    "job_position",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Job Position",
                    ),
                ),
                (
                    "bussines_area",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Bussines Area",
                    ),
                ),
                (
                    "self_description",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Self Description",
                    ),
                ),
                (
                    "job_expectation",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Job Expectation",
                    ),
                ),
                (
                    "programming_lang",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Programming Language",
                    ),
                ),
                (
                    "last_framework",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Last Comoany Framework",
                    ),
                ),
                (
                    "last_post_experience",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Last Company Experience",
                    ),
                ),
                (
                    "last_comp_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Last Company Name",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Phone Code"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
